name: Axe DevTools Linter

on:
  workflow_dispatch: 
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - master
      - release/*
      - release_qa
      - development

jobs:
  axe-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Axe DevTools Linter
        uses: dequelabs/axe-linter-action@v1
        with:
          api_key: ${{ secrets.DEQUE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config-path: ./axe-linter-config.json  
