name: Axe DevTools Linter

on:
  pull_request:
    branches:
      - master
      - release/*
      - release_qa
      - development
  push:
    branches:
      - development

jobs:
  axe-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Axe DevTools Linter
        uses: dequelabs/axe-devtools-linter-action@v4
        with:
          api-key: ${{ secrets.DEQUE_API_KEY }}
          config-path: ./axe-linter-config.json
